### ISSUE TITLE
工作原理是啥呢

### ISSUE THREAD

**Issue by at86397388** [dr34-m/taosync#1]
工作原理是啥呢？是先下载到本地，然后再上传么？

**Comment by dr34-m** [comment]
分网盘，对于多数网盘或存储，可以直接从一个网盘到另一个网盘；但是对于夸克之类的网盘，必须经过本地代理（也就是你理解的下载到本地再上传），[原因](https://github.com/alist-org/alist/issues/4318)。

以上结论基于对[AList](https://github.com/alist-org/alist)调研所得，未必正确，欢迎指正。

**Comment by at86397388** [comment]
pikpak到天翼云盘呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: notifications ***@***.***&gt;
发送时间: 2024年7月23日 08:53
收件人: dr34-m/taosync ***@***.***&gt;
抄送: at86397388 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)





 
分网盘，对于多数网盘或存储，可以直接从一个网盘到另一个网盘；但是对于夸克之类的网盘，必须经过本地代理（也就是你理解的下载到本地再上传），原因。
 
以上结论基于对AList调研所得，未必正确，欢迎指正。

**Comment by dr34-m** [comment]
应该是不经过本地代理，更多详情可见[AList文档-三种模式说明](https://alist.nn.ci/zh/guide/drivers/common.html#%E4%B8%89%E7%A7%8D%E6%A8%A1%E5%BC%8F%E8%AF%B4%E6%98%8E)

**Comment by at86397388** [comment]
好的，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: notifications ***@***.***&gt;
发送时间: 2024年7月23日 10:16
收件人: dr34-m/taosync ***@***.***&gt;
抄送: at86397388 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)





 
应该是不经过本地代理，更多详情可见AList文档-三种模式说明

**Comment by at86397388** [comment]
这个程序其实还是调用的alist自身的复制功能哈，就是我创建了作业，就相当于在alist后台创建了复制任务，如果我禁止了作业，alist的复制作业还是在么？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: notifications ***@***.***&gt;
发送时间: 2024年7月23日 10:16
收件人: dr34-m/taosync ***@***.***&gt;
抄送: at86397388 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)





 
应该是不经过本地代理，更多详情可见AList文档-三种模式说明

**Comment by dr34-m** [comment]
如果存在未结束的任务，您禁止作业，此时复制任务仍然存在，将会继续复制











发自我的iPhone

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月24日(周三) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)




 这个程序其实还是调用的alist自身的复制功能哈，就是我创建了作业，就相当于在alist后台创建了复制任务，如果我禁止了作业，alist的复制作业还是在么？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: notifications ***@***.***&amp;gt; 
 发送时间: 2024年7月23日 10:16 
 收件人: dr34-m/taosync ***@***.***&amp;gt; 
 抄送: at86397388 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
 主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1) 
 
 
 
 
 
   
 应该是不经过本地代理，更多详情可见AList文档-三种模式说明

**Comment by at86397388** [comment]
请问，docker运行起来为什么会产生特别多的log文件呢而且每个log文件都很大，50多兆，动不动就提示没有空间的错误，我设置的间隔是720分钟



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xinxinenjoy ***@***.***&gt;
发送时间: 2024年7月24日 21:01
收件人: dr34-m/taosync ***@***.***&gt;
抄送: at86397388 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)





 如果存在未结束的任务，您禁止作业，此时复制任务仍然存在，将会继续复制 
 
 
 
 
 
 
 
 
 
 
 
 发自我的iPhone 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年7月24日(周三) 上午10:18 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1) 
 
 
 
 
  这个程序其实还是调用的alist自身的复制功能哈，就是我创建了作业，就相当于在alist后台创建了复制任务，如果我禁止了作业，alist的复制作业还是在么？  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: notifications ***@***.***&amp;amp;gt;  
  发送时间: 2024年7月23日 10:16  
  收件人: dr34-m/taosync ***@***.***&amp;amp;gt;  
  抄送: at86397388 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
  主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)  
   
   
   
   
   
     
  应该是不经过本地代理，更多详情可见AList文档-三种模式说明

**Comment by at86397388** [comment]
特别是alist日志



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: notifications ***@***.***&gt;
发送时间: 2024年7月24日 21:01
收件人: dr34-m/taosync ***@***.***&gt;
抄送: at86397388 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)





 如果存在未结束的任务，您禁止作业，此时复制任务仍然存在，将会继续复制 
 
 
 
 
 
 
 
 
 
 
 
 发自我的iPhone 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年7月24日(周三) 上午10:18 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1) 
 
 
 
 
  这个程序其实还是调用的alist自身的复制功能哈，就是我创建了作业，就相当于在alist后台创建了复制任务，如果我禁止了作业，alist的复制作业还是在么？  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: notifications ***@***.***&amp;amp;gt;  
  发送时间: 2024年7月23日 10:16  
  收件人: dr34-m/taosync ***@***.***&amp;amp;gt;  
  抄送: at86397388 ***@***.***&amp;amp;gt;, Author ***@***.***&amp;amp;gt;  
  主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)  
   
   
   
   
   
     
  应该是不经过本地代理，更多详情可见AList文档-三种模式说明

**Comment by dr34-m** [comment]
可以尝试调低日志自动清理间隔，
TAO_LOG_SAVE
默认为7，即自动清理7天前的日志，你可以调整低一点

**Comment by at86397388** [comment]
tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.







请问这个是啥错误啊？怎么解决啊






发自我的iPhone


------------------ 原始邮件 ------------------
发件人: notifications ***@***.***&gt;
发送时间: 2024年8月12日 10:59
收件人: dr34-m/taosync ***@***.***&gt;
抄送: at86397388 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dr34-m/taosync] 工作原理是啥呢 (Issue #1)





 
可以尝试调低日志自动清理间隔，
 TAO_LOG_SAVE
 默认为7，即自动清理7天前的日志，你可以调整低一点

**Comment by dr34-m** [comment]
请创建新的issue提出新的问题，不然不方便归档记录
