### ISSUE TITLE
未知原因导致每次同步会有大量的失败

### ISSUE THREAD

**Issue by longbill** [dr34-m/taosync#2]
![WX20240725-172748](https://github.com/user-attachments/assets/72eca3ab-0d12-4a76-8a3e-125e5e2c5d6a)
![WX20240725-172800](https://github.com/user-attachments/assets/bb5dc925-e0fa-4e8c-ae58-b0025678fa85)

同步的来源是alist通过docker共享过去的本地数据，同步目的地是alist百度网盘。

**Comment by dr34-m** [comment]
你好，根据截图来看，猜测是你在同步的过程中，手动删除AList中的记录，导致本程序找不到任务记录，判定同步失败导致的。建议不要手动到AList删除成功的任务。本程序读取之后会自动删除本程序发起的AList任务的记录的。

**Comment by dr34-m** [comment]
另外部分网盘（百度网盘目前没出现过）实测也偶尔会出现失败的情况，但是也不用担心，下次同步时会自动同步失败的项目，慢慢总能成功的（除非文件存在违规之类的原因）。

同步较多文件时耗时较长，在此期间不建议操作AList进行复制等任务（AList限制同时只能进行有限个复制任务），更不能删除任务记录，否则本程序就读取不到其状态了。

一般第一次同步会有大量文件，可能会比较有感，之后同步基本都是无感的，不影响正常使用AList。

**Comment by longbill** [comment]
@dr34-m 同步过程我完全没有动alist哦

**Comment by longbill** [comment]
你的意思是复制操作是由alist完成的？  taosync只是把复制任务提交给了alist?

**Comment by dr34-m** [comment]
是的，taoSync读取AList中的文件，对比差异，把需要复制的项目告诉AList，由AList完成复制任务，taoSync定时读取AList中的任务状态。

**Comment by longbill** [comment]
哈哈，果然我在alist里面看到了复制任务。

**Comment by dr34-m** [comment]
所以你有在AList中删除过复制任务吗，比如点击删除成功项之类的？

**Comment by longbill** [comment]
> 所以你有在AList中删除过复制任务吗，比如点击删除成功项之类的？

没有

**Comment by dr34-m** [comment]
那就很奇怪了，那是否有操作重启AList呢，好像重启AList也会导致任务被清空。或者检查下AList的日志，是否有异常挂掉导致自动重启之类的

**Comment by dr34-m** [comment]
> > 所以你有在AList中删除过复制任务吗，比如点击删除成功项之类的？
> 
> 没有

当然，你也可以选择忽略它，因为多同步些次数，总能全部成功的

**Comment by longbill** [comment]
果然alist容器有重启。 而且还看到很多错误日志。
![image](https://github.com/user-attachments/assets/5a1a5d9e-adfc-4bb8-a377-9411ba13f9f2)

**Comment by longbill** [comment]
果然alist容易有重启。而且还看到很多错误日志。
![image](https://github.com/user-attachments/assets/ea19ce02-a474-4c78-909a-e1e117f87e99)

**Comment by longbill** [comment]
看起来像是复制大文件的时候超时了？

**Comment by dr34-m** [comment]
> 看起来像是复制大文件的时候超时了？

确实有这种可能，还有可能是访问百度网盘过于频繁被临时限制了，建议暂时忽略它，慢慢总会全部成功的。

还可以尝试去alist提issue

**Comment by longbill** [comment]
alist已经有人提了。 暂时还没解决。   https://github.com/alist-org/alist/issues/6149

感谢。我把这个issue关了
