### ISSUE TITLE
win10 python如何启动？

### ISSUE THREAD

**Issue by gaodyoffice** [dr34-m/taosync#3]
win10 直接python main.py后进入http://127.0.0.1:8023/
报这个错误 500: Internal Server Error

**Comment by dr34-m** [comment]
因为前端没有打包，你需要打包前端后，放到main.py同级下的front目录，然后启动











发自我的iPhone

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月10日(周六) 上午9:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dr34-m/taosync] win10 python如何启动？ (Issue #3)




 
win10 直接python main.py后进入http://127.0.0.1:8023/
 报这个错误 500: Internal Server Error

**Comment by gaodyoffice** [comment]
好的，知道了，谢谢。

**Comment by gaodyoffice** [comment]
没搞定😂，大佬下个版本有计划打包吗？

**Comment by dr34-m** [comment]
> 没搞定😂，大佬下个版本有计划打包吗？

目前仅能手动打包，暂时没找到合适的自动化打包方案

**Comment by dr34-m** [comment]
已经发布windows版本（预发布），可以前往下载测试了[Release](https://github.com/dr34-m/taosync/releases)
