### ISSUE TITLE
修改密码以后无法登录

### ISSUE THREAD

**Issue by lxjxxxxxxxx** [dr34-m/taosync#4]
修改密码后登录显示'NoneType' object has no attribute 'copy'

**Comment by ceozero** [comment]
同样的问题，无法修改密码。。。。用户名也无法修改。

**Comment by dr34-m** [comment]
已确认这个问题，临时可以通过删除浏览器cookie或者更换浏览器解决，将在下个版本彻底修复。

用户名暂不支持修改

**Comment by dr34-m** [comment]
已修复该问题，请删除原容器与镜像，重新拉取最新镜像即可。

只需要挂载原来的目录，原来的数据与配置就都还在，不会丢失
