### ISSUE TITLE
Can not find any timezone configuration, defaulting to UTC.

### ISSUE THREAD

**Issue by at86397388** [dr34-m/taosync#5]
tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.

请问这个是啥错误啊？怎么解决啊

**Comment by dr34-m** [comment]
时区没有设定使用了默认时区UTC，如果没有使用cron方式的定时任务的话，通常你不需要关注，因为不会影响程序的正常运行

如果确实需要，可以添加环境变量来指定时区，例如在国内一般是

`TZ`=`Asia/Shanghai`

**Comment by at86397388** [comment]
请问生成alist日志的作用是啥，可以禁止生成么？



发自我的iPhone


------------------ Original ------------------
From: notifications ***@***.***&gt;
Date: Tue,Aug 13,2024 10:49 AM
To: dr34-m/taosync ***@***.***&gt;
Cc: at86397388 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dr34-m/taosync] Can not find any timezone configuration,defaulting to UTC. (Issue #5)





 
时区没有设定使用了默认时区UTC，如果没有使用cron方式的定时任务的话，通常你不需要关注，因为不会影响程序的正常运行
 
如果确实需要，可以添加环境变量来指定时区，例如在国内一般是
 
TZ=Asia/Shanghai

**Comment by dr34-m** [comment]
可以看下日志文件的名称和目录吗？

**Comment by at86397388** [comment]
主要是alist/log/下的，用了taosync以后日志特别多，且文件大



发自我的iPhone


------------------ Original ------------------
From: notifications ***@***.***&gt;
Date: Wed,Aug 14,2024 1:43 PM
To: dr34-m/taosync ***@***.***&gt;
Cc: at86397388 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dr34-m/taosync] Can not find any timezone configuration,defaulting to UTC. (Issue #5)





 
可以看下日志文件的名称和目录吗？

**Comment by dr34-m** [comment]
可以参考alist官方文档关闭日志

[log](https://alist.nn.ci/zh/config/configuration.html#log)
