### ISSUE TITLE
今天总出现这个错误

### ISSUE THREAD

**Issue by ppllpig** [dr34-m/taosync#8]
执行任务失败，原因为：AList返回500错误，原因为：Loading storage, please wait_/_Task execution failed due to: AList returns 500, reason: Loading storage, please wait
重启任务也是

**Comment by ppllpig** [comment]
正在排查是不是双宽带爱快分流导致的~

**Comment by dr34-m** [comment]
看起来是你所使用的存储出了问题，可以尝试到alist中检查存储状态
