### ISSUE TITLE
无需同步

### ISSUE THREAD

**Issue by nigo81** [dr34-m/taosync#9]
我同步两个文件夹，显示的都是无需同步。
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/0b06c8f3-2ca8-4773-8f59-4b5c18f3d122">
而两个文件夹内容是不一样的，不能同步。日志信息：
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/292d4208-78ea-48c0-bd84-1ada12f2c610">

**Comment by dr34-m** [comment]
提供的信息太少了，没法判断问题。建议你尝试以下操作：

* 检查下选择的来源文件夹与目标文件夹是否正确
* 打开alist，访问对应文件夹检查文件时候有差异
* 发送更详细的日志文件（截图中就10行日志文件来回重复，且都是与同步任务无关文件）

**Comment by dr34-m** [comment]
经过验证该问题确实存在，将在下个版本修复

**Comment by nigo81** [comment]
好的，因为开始想手动测试下，没注意是否和禁用状态有关，最开始我没禁用的时候好像也不行，到时候我再测试下。另外就是感觉扫描的速度很慢，测试的这里面文件并不是很多。

**Comment by dr34m-cn** [comment]
已修复该问题（调用方式增加仅手动选项，禁用的任务不允许手动执行）
